version: "3.9"

services:
  app:
    build: .
    container_name: amzn-linux-2
    privileged: true
    volumes:
      - type: bind
        source: ./work
        target: /home/ec2-user/work
      - type: bind
        source: ./.aws
        target: /home/ec2-user/.aws