version: "3.9"

services:
  app:
    build: .
    container_name: amzn-linux-2
    privileged: true
    restart: always
    volumes:
      - type: bind
        source: ./myapp
        target: /home/ec2-user/myapp
      - type: bind
        source: ./.aws
        target: /home/ec2-user/.aws