version: "3.9"

services:
  amzn-linux-2:
    build: .
    container_name: amzn-linux-2
    privileged: true
    restart: always
    volumes:
      - type: bind
        source: ./share
        target: /share
      - type: bind
        source: ./.aws
        target: /home/ec2-user/.aws